import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const DEFAULT_CLIENT_ID = "dcb56eca385c5c3f61a355d8f59a3456";
const LIVE_SCOPES = [
  "read_orders",
  "read_locations",
  "read_merchant_managed_fulfillment_orders",
];

function requiredEnv(name) {
  const value = process.env[name]?.trim();

  if (!value) {
    throw new Error(`${name} is required.`);
  }

  return value;
}

function normalizeHttpsOrigin(rawUrl) {
  let url;

  try {
    url = new URL(rawUrl);
  } catch {
    throw new Error(
      `SHOPIFY_APP_URL must be a valid absolute URL. Received: ${rawUrl}`,
    );
  }

  if (url.protocol !== "https:") {
    throw new Error("SHOPIFY_APP_URL must use https for real-store installs.");
  }

  if (url.hostname === "example.com" || url.hostname.endsWith(".example.com")) {
    throw new Error("SHOPIFY_APP_URL cannot be an example.com placeholder.");
  }

  url.pathname = "";
  url.search = "";
  url.hash = "";

  return url.origin;
}

function writeLiveConfig() {
  const appUrl = normalizeHttpsOrigin(requiredEnv("SHOPIFY_APP_URL"));
  const clientId =
    process.env.SHOPIFY_LIVE_CLIENT_ID?.trim() || DEFAULT_CLIENT_ID;
  const scopes = LIVE_SCOPES.join(",");

  const toml = `# Generated by scripts/live-config.mjs. Do not commit the generated file.

client_id = "${clientId}"
application_url = "${appUrl}"
embedded = true
name = "COG Order Printer"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/fulfillment-orders/order-routing-complete"
  topics = [ "fulfillment_orders/order_routing_complete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/fulfillment-orders/moved"
  topics = [ "fulfillment_orders/moved" ]

[access_scopes]
scopes = "${scopes}"

[auth]
redirect_urls = [ "${appUrl}/auth/callback" ]
`;

  writeFileSync("shopify.app.live.toml", toml);

  console.log("Wrote shopify.app.live.toml");
  console.log(`Application URL: ${appUrl}`);
  console.log(`Scopes: ${scopes}`);
}

writeLiveConfig();

if (process.argv.includes("--deploy")) {
  execFileSync(
    "shopify",
    ["app", "deploy", "--config", "live", "--allow-updates"],
    {
      stdio: "inherit",
    },
  );
}
